# -*- coding: utf-8 -*-
"""agriculture crop recognation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11TLO1s7-JY5pzHxP1tI21E_WsKRHMIV_
"""

from google.colab import drive
drive.mount('/content/drive')

import os

img1 = os.listdir('/content/drive/MyDrive/agriculture_crop_img/crop_images')

a = []
for i in img1:
  a.append(i)

a

from tensorflow.keras.preprocessing.image import ImageDataGenerator
import pandas as pd
from tensorflow.keras.applications import VGG16

vgg16_obj = VGG16(include_top = False, input_shape = (224,224,3))    
for layer in vgg16_obj.layers:             
    layer.trainable = False
vgg16_obj.summary()

vgg16_obj.output

from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense,Flatten
f1 = Flatten()(vgg16_obj.output)
final_layer = Dense(5, activation='softmax')(f1)
final_layer

model = Model(inputs=vgg16_obj.input,outputs=final_layer)
model.summary()

from tensorflow.keras.preprocessing.image import ImageDataGenerator

crop_datagen = ImageDataGenerator(rescale=1/255,
                                  shear_range=0.7,
                                  zoom_range=0.5)

crop_datagen = ImageDataGenerator(rescale=1/255,
                                 horizontal_flip=True,
                                 vertical_flip=True, rotation_range=40,
                                 shear_range=0.2,zoom_range=0.3)

path='../content/drive/MyDrive/agriculture_crop_img/crop_images'
crop_data =crop_datagen.flow_from_directory(
    directory=path,
    target_size=(224,224),
    batch_size=3,
    class_mode="categorical",)

crop_data.class_indices

model.compile(loss='categorical_crossentropy', metrics=['accuracy'])

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten

model = Sequential()
model.add(Conv2D(16,(3,3),activation='relu',input_shape=(224,224,3)))
model.add(MaxPool2D())
model.add(Conv2D(32,(3,3),activation='relu'))
model.add(MaxPool2D()) 
model.add(Flatten())
model.add(Dense(5, activation='softmax'))

model.compile(
  loss='categorical_crossentropy',
  optimizer='adam',
  metrics=['accuracy'])

model.fit_generator(crop_data, epochs=75)

model.save('Crop_Prediction Vgg16_97%')

import cv2

def get_class(path):
    A=cv2.imread(path)
    A=cv2.resize(A,(224,224))
    A= A.reshape(1,224,224,3)/255
    print(model.predict(A))
    if model.predict(A).argmax()==0:
        return('jute')
    elif model.predict(A).argmax()==1:
        return('maize')
    elif model.predict(A).argmax()==2:
        return('rice')
    elif model.predict(A).argmax()==3:
        return('sugarcane')
    elif model.predict(A).argmax()==4:
        return('wheat')

def predict(path):
    A=cv2.imread(path)
    A=cv2.resize(A,(224,224))/255
    y=vgg_model2.predict_on_batch(A.reshape(1,224,224,3)).argmax()
    if y==0:
        return 'jute'
    if y==1:
        return 'maize'
    if y==2:
        return 'rice'
    if y==3:
        return 'sugarcane'
    if y==4:
        return 'wheat'

get_class('/content/drive/MyDrive/agriculture_crop_img/test_crop_image/sugarcane-farm-in-the-mountain-countryside-of-thailand.jpg')

get_class('/content/drive/MyDrive/agriculture_crop_img/test_crop_image/wheat-field01.jpg')

get_class('/content/drive/MyDrive/agriculture_crop_img/test_crop_image/rice-field.jpg')



